version: "3.8"

services:
  web:
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: sleep infinity
    volumes:
      - ./:/usr/src/workindir/
      - ${USERPROFILE}/.ssh:/root/.ssh:rw # para windows
    ports:
      - 8000:8000

