# Generated by Django 3.2.25 on 2024-06-24 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sql_query', models.TextField(blank=True, null=True)),
                ('bi_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('date', 'Date'), ('boolean', 'Boolean'), ('choice_list', 'Choice List'), ('multiple_choice', 'Multiple Choice'), ('json', 'JSON or Dict')], max_length=50)),
                ('required', models.BooleanField(default=False)),
                ('data', models.CharField(blank=True, help_text='List of data to select from in case of choice list or multiple choice, use the convention app.model to generate data from an existing model', max_length=500, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='dynamic_report.report')),
            ],
        ),
    ]
